### ISSUE TITLE
Question about Theorem 2

### ISSUE THREAD

**Issue by badbadcode** [ghzhang233/Non-Discrimination-Learning-for-Text-Classification#13]
Thanks for your work!

I have one question on the proof of **Theorem 2**. I wonder why the second equation shown in this figure holds . Am I missing some important points here?

![image](https://user-images.githubusercontent.com/38687930/144380049-0863ab99-1f34-4102-9782-81663442bc7a.png)

Looking forward to your reply.

**Comment by ghzhang233** [comment]
Sorry for the confusion. It may be easier to understand in the following derivation. Please feel free to leave a message if there's anything else that I failed to clarify.
![image](https://user-images.githubusercontent.com/15927725/144390223-462f7c34-4602-4f84-ba2b-f99b16a69178.png)

**Comment by ghzhang233** [comment]
I am going to close this issue. Please feel free to open another issue if there are any other problems.

**Comment by badbadcode** [comment]
Very clear! Thanks a lot!
