### ISSUE TITLE
Gender General/Extra Swap Files

### ISSUE THREAD

**Issue by Ago3** [ghzhang233/Non-Discrimination-Learning-for-Text-Classification#7]
Hi,

I'm trying to replicate the results for the Sexist Tweets from your work, but I'm having some issues with the IPTTS.

First of all, are the files needed for the procedure the following ones:
https://github.com/uclanlp/corefBias/blob/master/WinoBias/wino/generalized_swaps.txt
https://github.com/uclanlp/corefBias/blob/master/WinoBias/wino/extra_gendered_words.txt

And second, what further pre-processing is needed besides removing duplicates? Because in the code male nouns are selected on the basis of their index, while both the columns in the files contain male and female nouns.

Thank you!

**Comment by ghzhang233** [comment]
Hi, @Ago3 ,

Thank you for your interest in our work!

For your first question, yes, they are. For the second question, you need to swap those irregular ones by hand.

Let me know if there is still something unclear. I am happy to help!

**Comment by Ago3** [comment]
Thank you very much for the kind (and quick) reply!

Did you also fix spelling errors (e.g., "mentleman") in those files?

**Comment by ghzhang233** [comment]
Hi, @Ago3 . Sorry for missing this. Yes, I did.
